#config.yaml
flows:
  - budidaya/penyakit/*
excludeTags:
  - login
  - ATAIR
  - ATPAKAN
  - ATDELPAKAN
  - ATANCO
  - ATKEM

executionOrder:
    continueOnFailure: false
    flowsOrder:
        - AT53-55
