#config.yaml
flows:
  - "**"
includeTags:
  - AT47-AT49
excludeTags:
  - login
  - AT2
  - AT3
  - AT5
  - AT6
  - AT7
  - AT9
  - AT10
  - AT11
  - AT12
  - AT13
  - AT14
  - AT15
  - AT16
  - AT17
  - AT18
  - AT19
  - AT20
  - AT21
  - AT22
