#config.yaml
flows:
  - budidaya/kualitas_air/*
excludeTags:
  - login
  - ATANCO
  - ATDELPAKAN
  - ATPAKAN
  - ATKEM

executionOrder:
    continueOnFailure: false
    flowsOrder:
        - AT23CRUD
