#config.yaml
flows:
  - "**"
includeTags:
  - AT23-25
  - AT53-54
  - AT55
excludeTags:
  - login
  - AT26-27
  - AT28-30
  - AT31
  - AT41-43

executionOrder:
    continueOnFailure: false
    flowsOrder:
        - AT23-25
        - AT53-54
        - AT55

