#config.yaml
flows:
  - budidaya/pakan/*
excludeTags:
  - login
  - ATANCO
  - ATAIR
  - ATKEM
  - ATDELETEPAKAN
  - ATPAKAN

executionOrder:
    continueOnFailure: false
    flowsOrder:
        - AT31
