#config.yaml
flows:
  - "**"
includeTags:
  - AT2
excludeTags:
  - login
  - AT2
  - AT3
  - AT5
  - AT6
  - AT7
  - AT9
  - AT10
  - AT11
  - AT12
  - AT13
  - AT14
  - AT15
  - AT16
  - AT17
  - AT18
  - AT19
  - AT20
  - AT21
  - AT22
  - AT47-AT49

  #File config.yaml ini diperlukan untuk menentukan:
  #1. test apa saja yang ingin diikut sertakan
  #2. untuk kasus tes crud yang kemungkinan ada beberapa test yang memiliki keterkaitan saling bergantung pada test lain,
  #   dalam file config.yaml ini dapat menentukan executionOrder untuk menentukan urutan test yang ingin diurutkan
  #3. Untuk lengkapnya mengenai cara konfigurasi ada di docs maestro ui testing
